---
title: "Laminaria japonica"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

## Time series of observations
library(flexdashboard)
source(here::here("R","taxo-network.R"))
dat <- data_for_focus("Chromista;Ochrophyta;Phaeophyceae;Laminariales;Laminariaceae;Laminaria;Laminaria_japonica")

REALM_list<-dat[!is.na(REALM),unique(REALM)|>as.character()]
my_cols<-RColorBrewer::brewer.pal(12,"Set3")  
names(my_cols) <- REALM_list
  
most_abund_realm<- dat %>% 
  dplyr::filter(REALM != "NA") %>% 
  dplyr::mutate(year = round_date(eventDate,unit = "year")) %>%
  dplyr::group_by(REALM) %>%
  dplyr::summarise(obs = n()) %>% 
  dplyr::arrange(., desc(obs)) %>%
  dplyr::slice_head(n = 5) %>%
  select(REALM)

observations<- dat %>% 
  dplyr::filter(REALM != "NA") %>% 
  dplyr::mutate(year = lubridate::round_date(eventDate,unit = "year")) %>%
  dplyr::group_by(REALM, year) %>%
  dplyr::summarise(obs = n()) %>% 
  tidyr::pivot_wider(names_from = REALM, values_from = obs) %>% 
  tibble::column_to_rownames(var = "year") %>%
  dplyr::select(most_abund_realm$REALM)

colours<- dplyr::left_join(most_abund_realm, 
    tibble::rownames_to_column(as.data.frame(my_cols), "REALM"))
  
dygraphs::dygraph(observations, main = "") %>% 
  dygraphs::dyRangeSelector()%>% 
  dyOptions(colors = colours$my_cols) %>% 
  dyAxis("y", label = "Observations per year")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

## Abundance per ecoregion 

library(ggplot2)

abundance <-dat %>% 
  dplyr::filter(REALM != "NA") %>% 
  dplyr::mutate(year = lubridate::round_date(eventDate,unit = "year")) %>%
  dplyr::group_by(REALM) %>%
  dplyr::summarise(obs = n()) %>%
  dplyr::arrange(., desc(obs))%>%
  dplyr::filter(obs > 0 )

p <- ggplot(data = abundance, aes(y = REALM, x = obs)) +
        geom_col(aes(fill = REALM))+
  scale_y_discrete(limits=abundance$REALM |> rev()) +
  scale_fill_manual(values = my_cols) +
  scale_x_continuous(name="Observations")
  

plotly::ggplotly(p)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

## global occurrence 

library(leaflet)

leaflet(options = leafletOptions(minZoom = 0, maxZoom = 18)) %>% 
  leaflet() %>% addCircles(data = dat, lat = ~ decimalLatitude, lng = ~ decimalLongitude, color = "black")%>% 
  addTiles()

# colours <- tibble::rownames_to_column(as.data.frame(my_cols), "REALM")
# pal <- colorFactor(c(colours$my_cols), domain = c(colours$REALM))
# factpal <- colorFactor(colours$my_cols, colours$REALM)

# leaflet(options = leafletOptions(minZoom = 0, maxZoom = 18)) %>% 
#  leaflet() %>% addCircles(data = dat, lat = ~ decimalLatitude, lng = ~ decimalLongitude, color = ~factpal(REALM))%>% 
#  addTiles() %>% 
#  addLegend("bottomright", pal = factpal, values = ~REALM)

```

### Chart C

```{r}

```

