---
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
params:
  tax: "Chromista;Ochrophyta;Phaeophyceae;Laminariales;Laminariaceae;Laminaria;Laminaria_japonica"
---

```{r setup, include=FALSE}
library(flexdashboard)
label <- sub("^.+;","",params$tax)

source(here::here("R","taxo-network.R"))
dat <- data_for_focus(params$tax)
```

```{r}
if(nrow(dat)!=0){
  REALM_list<-dat[!is.na(REALM),unique(REALM)|>as.character()]
my_cols<-RColorBrewer::brewer.pal(12,"Set3")  
names(my_cols) <- REALM_list
  
most_abund_realm<- dat |> 
  dplyr::filter(REALM != "NA") |> 
  dplyr::mutate(year = lubridate::round_date(eventDate,unit = "year")) |>
  dplyr::group_by(REALM) |>
  dplyr::summarise(obs = dplyr::n()) |> 
  dplyr::arrange(dplyr::desc(obs)) |>
  dplyr::slice_head(n = 5) |>
  dplyr::select(REALM)

observations<- dat |> 
  dplyr::filter(REALM != "NA") |> 
  dplyr::mutate(year = lubridate::round_date(eventDate,unit = "year")) |>
  dplyr::group_by(REALM, year) |>
  dplyr::summarise(obs = dplyr::n()) |> 
  tidyr::pivot_wider(names_from = REALM, values_from = obs) |> 
  tibble::column_to_rownames(var = "year") |>
  dplyr::select(most_abund_realm$REALM)

abundance <-dat |> 
  dplyr::filter(REALM != "NA") |> 
  dplyr::mutate(year = lubridate::round_date(eventDate,unit = "year")) |>
  dplyr::group_by(REALM) |>
  dplyr::summarise(obs = dplyr::n()) |>
  dplyr::arrange(dplyr::desc(obs))|>
  dplyr::filter(obs > 0 )

colours<- dplyr::left_join(most_abund_realm, 
    tibble::rownames_to_column(as.data.frame(my_cols), "REALM"))

}
```

---
title: "`r label`"
---

Column {data-width=650}
-----------------------------------------------------------------------

### Map

```{r}
if(nrow(dat)!=0){
  library(leaflet)

leaflet(options = leafletOptions(minZoom = 0, maxZoom = 18)) |> 
  leaflet() |> addCircles(data = dat, lat = ~ decimalLatitude, lng = ~ decimalLongitude, color = "black")|> 
  addTiles()
}
```

Column {data-width=350}
-----------------------------------------------------------------------

### Observations per realm

```{r}
if(nrow(dat)!=0){
  ## Abundance per ecoregion 

library(ggplot2)

p <- ggplot(data = abundance, aes(y = REALM, x = obs)) +
        geom_col(aes(fill = REALM))+
  scale_y_discrete(limits=abundance$REALM |> rev()) +
  scale_fill_manual(values = my_cols) +
  scale_x_continuous(name="Observations")
  

plotly::ggplotly(p)
}
```

### Observations overtime

```{r}
if(nrow(dat)!=0){
  dygraphs::dygraph(observations, main = "") |> 
  dygraphs::dyRangeSelector()|> 
  dygraphs::dyOptions(colors = colours$my_cols) |> 
  dygraphs::dyAxis("y", label = "Observations per year")
}
```
